linux/inet.h is required for in_aton()
error message:
/home/mitake/github/sheepdog.git/sheepdev/connect.c: In function ‘connect_to’:
/home/mitake/github/sheepdog.git/sheepdev/connect.c:31: error: implicit declaration of function ‘in_aton’